Traceback (most recent call last):
  File "C:\Users\KenoK\PycharmProjects\gaussbot\gauss\bot.py", line 77, in on_message
    if message.attachments.first():
AttributeError: 'list' object has no attribute 'first'

Traceback (most recent call last):
  File "C:\Users\KenoK\PycharmProjects\gaussbot\gauss\bot.py", line 77, in on_message
    if message.attachments.first():
AttributeError: 'list' object has no attribute 'first'

Traceback (most recent call last):
  File "C:\Users\KenoK\PycharmProjects\gaussbot\gauss\bot.py", line 77, in on_message
    if message.attachments.first():
AttributeError: 'list' object has no attribute 'first'

Traceback (most recent call last):
  File "C:\Users\KenoK\PycharmProjects\gaussbot\gauss\bot.py", line 77, in on_message
    if message.attachments.first():
AttributeError: 'list' object has no attribute 'first'

Traceback (most recent call last):
  File "C:\Users\KenoK\PycharmProjects\gaussbot\gauss\bot.py", line 77, in on_message
    if message.attachments.first():
AttributeError: 'list' object has no attribute 'first'

Traceback (most recent call last):
  File "C:\Users\KenoK\PycharmProjects\gaussbot\gauss\bot.py", line 77, in on_message
    if message.attachments.first():
AttributeError: 'list' object has no attribute 'first'

Traceback (most recent call last):
  File "C:\Users\KenoK\PycharmProjects\gaussbot\gauss\bot.py", line 77, in on_message
    if message.attachments.first():
AttributeError: 'list' object has no attribute 'first'

Traceback (most recent call last):
  File "C:\Users\KenoK\PycharmProjects\gaussbot\gauss\bot.py", line 77, in on_message
    if message.attachments.first():
AttributeError: 'list' object has no attribute 'first'

Traceback (most recent call last):
  File "C:\Users\KenoK\PycharmProjects\gaussbot\gauss\bot.py", line 67, in on_message
    response["intvar"] = to_sympy(answer.content)
  File "C:\Users\KenoK\PycharmProjects\gaussbot\gauss\parse.py", line 21, in to_sympy
    return parse_expr(message, transformations=transformations,
  File "C:\Users\KenoK\Anaconda3\envs\gaussbot\lib\site-packages\sympy\parsing\sympy_parser.py", line 1008, in parse_expr
    return eval_expr(code, local_dict, global_dict)
  File "C:\Users\KenoK\Anaconda3\envs\gaussbot\lib\site-packages\sympy\parsing\sympy_parser.py", line 902, in eval_expr
    expr = eval(
  File "<string>", line 1
    \Symbol ('s' )*Symbol ('h' )*Symbol ('o' )*Symbol ('w' )*Symbol ('b' )*e *Symbol ('a' )*Symbol ('u' )*Symbol ('t' )*Symbol ('y' )
                                                                                                                                    ^
SyntaxError: unexpected character after line continuation character

Traceback (most recent call last):
  File "C:\Users\KenoK\PycharmProjects\gaussbot\gauss\bot.py", line 77, in on_message
    if message.attachments.first():
AttributeError: 'list' object has no attribute 'first'

Traceback (most recent call last):
  File "C:\Users\KenoK\PycharmProjects\gaussbot\gauss\bot.py", line 77, in on_message
    if message.attachments.first():
AttributeError: 'list' object has no attribute 'first'

Traceback (most recent call last):
  File "C:\Users\KenoK\PycharmProjects\gaussbot\gauss\bot.py", line 77, in on_message
    if message.attachments.first():
AttributeError: 'list' object has no attribute 'first'

Traceback (most recent call last):
  File "C:\Users\KenoK\PycharmProjects\gaussbot\gauss\bot.py", line 77, in on_message
    if message.attachments.first():
AttributeError: 'list' object has no attribute 'first'

Traceback (most recent call last):
  File "C:\Users\KenoK\PycharmProjects\gaussbot\gauss\bot.py", line 77, in on_message
    if message.attachments.first():
AttributeError: 'list' object has no attribute 'first'

Traceback (most recent call last):
  File "C:\Users\KenoK\PycharmProjects\gaussbot\gauss\bot.py", line 77, in on_message
    if message.attachments.first():
AttributeError: 'list' object has no attribute 'first'

Traceback (most recent call last):
  File "C:\Users\KenoK\PycharmProjects\gaussbot\gauss\bot.py", line 77, in on_message
    if message.attachments.first():
AttributeError: 'list' object has no attribute 'first'

Traceback (most recent call last):
  File "C:\Users\KenoK\PycharmProjects\gaussbot\gauss\bot.py", line 77, in on_message
    if message.attachments.first():
AttributeError: 'list' object has no attribute 'first'

Traceback (most recent call last):
  File "C:\Users\KenoK\PycharmProjects\gaussbot\gauss\bot.py", line 77, in on_message
    if message.attachments.first():
AttributeError: 'list' object has no attribute 'first'

Traceback (most recent call last):
  File "C:\Users\KenoK\PycharmProjects\gaussbot\gauss\bot.py", line 77, in on_message
    if message.attachments.first():
AttributeError: 'list' object has no attribute 'first'

Traceback (most recent call last):
  File "C:\Users\KenoK\PycharmProjects\gaussbot\gauss\bot.py", line 77, in on_message
    if message.attachments.first():
AttributeError: 'list' object has no attribute 'first'

Traceback (most recent call last):
  File "C:\Users\KenoK\PycharmProjects\gaussbot\gauss\bot.py", line 77, in on_message
    if message.attachments.first():
AttributeError: 'list' object has no attribute 'first'

Traceback (most recent call last):
  File "C:\Users\KenoK\PycharmProjects\gaussbot\gauss\bot.py", line 77, in on_message
    if message.attachments.first():
AttributeError: 'list' object has no attribute 'first'

Traceback (most recent call last):
  File "C:\Users\KenoK\PycharmProjects\gaussbot\gauss\bot.py", line 77, in on_message
    if message.attachments.first():
AttributeError: 'list' object has no attribute 'first'

Traceback (most recent call last):
  File "C:\Users\KenoK\PycharmProjects\gaussbot\gauss\bot.py", line 77, in on_message
    return do_calculation(message)
  File "C:\Users\KenoK\PycharmProjects\gaussbot\gauss\brain.py", line 239, in do_calculation
    calculation = to_sympy(calculation_part, numerical=True)
  File "C:\Users\KenoK\PycharmProjects\gaussbot\gauss\parse.py", line 44, in to_sympy
    return N(parse_expr(message, transformations=transformations,
  File "C:\Users\KenoK\Anaconda3\envs\gaussbot\lib\site-packages\sympy\parsing\sympy_parser.py", line 1003, in parse_expr
    code = stringify_expr(s, local_dict, global_dict, transformations)
  File "C:\Users\KenoK\Anaconda3\envs\gaussbot\lib\site-packages\sympy\parsing\sympy_parser.py", line 886, in stringify_expr
    input_code = StringIO(s.strip())
AttributeError: 'list' object has no attribute 'strip'

Traceback (most recent call last):
  File "C:\Users\KenoK\PycharmProjects\gaussbot\gauss\bot.py", line 77, in on_message
    await do_calculation(message)
  File "C:\Users\KenoK\PycharmProjects\gaussbot\gauss\brain.py", line 240, in do_calculation
    return message.channel.send("{:.8E}".format(calculation))
TypeError: unsupported format string passed to ComplexInfinity.__format__

Traceback (most recent call last):
  File "C:\Users\KenoK\PycharmProjects\gaussbot\gauss\bot.py", line 77, in on_message
    await do_calculation(message)
  File "C:\Users\KenoK\PycharmProjects\gaussbot\gauss\brain.py", line 240, in do_calculation
    return message.channel.send("{:.8E}".format(calculation))
TypeError: unsupported format string passed to Mul.__format__

Traceback (most recent call last):
  File "C:\Users\KenoK\PycharmProjects\gaussbot\gauss\bot.py", line 77, in on_message
    await do_calculation(message)
  File "C:\Users\KenoK\PycharmProjects\gaussbot\gauss\brain.py", line 240, in do_calculation
    return message.channel.send("{:.8E}".format(calculation))
TypeError: unsupported format string passed to Mul.__format__

Traceback (most recent call last):
  File "C:\Users\KenoK\PycharmProjects\gaussbot\gauss\bot.py", line 79, in on_message
    if message.attachments.first():
AttributeError: 'list' object has no attribute 'first'

Traceback (most recent call last):
  File "C:\Users\KenoK\PycharmProjects\gaussbot\gauss\bot.py", line 59, in on_message
    response = do_integration(message)
  File "C:\Users\KenoK\PycharmProjects\gaussbot\gauss\brain.py", line 82, in do_integration
    integrand = to_sympy(integral)
  File "C:\Users\KenoK\PycharmProjects\gaussbot\gauss\parse.py", line 47, in to_sympy
    return N(parse_expr(message, transformations=transformations,
  File "C:\Users\KenoK\Anaconda3\envs\gaussbot\lib\site-packages\sympy\parsing\sympy_parser.py", line 1008, in parse_expr
    return eval_expr(code, local_dict, global_dict)
  File "C:\Users\KenoK\Anaconda3\envs\gaussbot\lib\site-packages\sympy\parsing\sympy_parser.py", line 902, in eval_expr
    expr = eval(
  File "<string>", line 0
    
    ^
SyntaxError: unexpected EOF while parsing

Traceback (most recent call last):
  File "C:\Users\KenoK\PycharmProjects\gaussbot\gauss\bot.py", line 59, in on_message
    response = do_integration(message)
  File "C:\Users\KenoK\PycharmProjects\gaussbot\gauss\brain.py", line 82, in do_integration
    integrand = to_sympy(integral)
  File "C:\Users\KenoK\PycharmProjects\gaussbot\gauss\parse.py", line 47, in to_sympy
    return N(parse_expr(message, transformations=transformations,
  File "C:\Users\KenoK\Anaconda3\envs\gaussbot\lib\site-packages\sympy\parsing\sympy_parser.py", line 1008, in parse_expr
    return eval_expr(code, local_dict, global_dict)
  File "C:\Users\KenoK\Anaconda3\envs\gaussbot\lib\site-packages\sympy\parsing\sympy_parser.py", line 902, in eval_expr
    expr = eval(
  File "<string>", line 0
    
    ^
SyntaxError: unexpected EOF while parsing

Traceback (most recent call last):
  File "C:\Users\KenoK\PycharmProjects\gaussbot\gauss\bot.py", line 59, in on_message
    response = do_integration(message)
  File "C:\Users\KenoK\PycharmProjects\gaussbot\gauss\brain.py", line 82, in do_integration
    integrand = to_sympy(integral)
  File "C:\Users\KenoK\PycharmProjects\gaussbot\gauss\parse.py", line 47, in to_sympy
    return N(parse_expr(message, transformations=transformations,
  File "C:\Users\KenoK\Anaconda3\envs\gaussbot\lib\site-packages\sympy\parsing\sympy_parser.py", line 1008, in parse_expr
    return eval_expr(code, local_dict, global_dict)
  File "C:\Users\KenoK\Anaconda3\envs\gaussbot\lib\site-packages\sympy\parsing\sympy_parser.py", line 902, in eval_expr
    expr = eval(
  File "<string>", line 0
    
    ^
SyntaxError: unexpected EOF while parsing

Traceback (most recent call last):
  File "C:\Users\KenoK\PycharmProjects\gaussbot\gauss\bot.py", line 79, in on_message
    if message.attachments.first():
AttributeError: 'list' object has no attribute 'first'

Traceback (most recent call last):
  File "C:\Users\KenoK\PycharmProjects\gaussbot\gauss\bot.py", line 79, in on_message
    if message.attachments.first():
AttributeError: 'list' object has no attribute 'first'

Traceback (most recent call last):
  File "C:\Users\KenoK\PycharmProjects\gaussbot\gauss\bot.py", line 59, in on_message
    response = do_integration(message)
  File "C:\Users\KenoK\PycharmProjects\gaussbot\gauss\brain.py", line 82, in do_integration
    integrand = to_sympy(integral)
  File "C:\Users\KenoK\PycharmProjects\gaussbot\gauss\parse.py", line 47, in to_sympy
    return N(parse_expr(message, transformations=transformations,
  File "C:\Users\KenoK\Anaconda3\envs\gaussbot\lib\site-packages\sympy\parsing\sympy_parser.py", line 1008, in parse_expr
    return eval_expr(code, local_dict, global_dict)
  File "C:\Users\KenoK\Anaconda3\envs\gaussbot\lib\site-packages\sympy\parsing\sympy_parser.py", line 902, in eval_expr
    expr = eval(
  File "<string>", line 0
    
    ^
SyntaxError: unexpected EOF while parsing

Traceback (most recent call last):
  File "C:\Users\KenoK\PycharmProjects\gaussbot\gauss\bot.py", line 59, in on_message
    response = do_integration(message)
  File "C:\Users\KenoK\PycharmProjects\gaussbot\gauss\brain.py", line 82, in do_integration
    integrand = to_sympy(integral)
  File "C:\Users\KenoK\PycharmProjects\gaussbot\gauss\parse.py", line 43, in to_sympy
    return parse_expr(message, transformations=transformations,
  File "C:\Users\KenoK\Anaconda3\envs\gaussbot\lib\site-packages\sympy\parsing\sympy_parser.py", line 1008, in parse_expr
    return eval_expr(code, local_dict, global_dict)
  File "C:\Users\KenoK\Anaconda3\envs\gaussbot\lib\site-packages\sympy\parsing\sympy_parser.py", line 902, in eval_expr
    expr = eval(
  File "<string>", line 0
    
    ^
SyntaxError: unexpected EOF while parsing

Traceback (most recent call last):
  File "C:\Users\KenoK\PycharmProjects\gaussbot\gauss\bot.py", line 59, in on_message
    response = do_integration(message)
  File "C:\Users\KenoK\PycharmProjects\gaussbot\gauss\brain.py", line 82, in do_integration
    integrand = to_sympy(integral)
  File "C:\Users\KenoK\PycharmProjects\gaussbot\gauss\parse.py", line 43, in to_sympy
    return parse_expr(message, transformations=transformations,
  File "C:\Users\KenoK\Anaconda3\envs\gaussbot\lib\site-packages\sympy\parsing\sympy_parser.py", line 1008, in parse_expr
    return eval_expr(code, local_dict, global_dict)
  File "C:\Users\KenoK\Anaconda3\envs\gaussbot\lib\site-packages\sympy\parsing\sympy_parser.py", line 902, in eval_expr
    expr = eval(
  File "<string>", line 0
    
    ^
SyntaxError: unexpected EOF while parsing

Traceback (most recent call last):
  File "C:\Users\KenoK\PycharmProjects\gaussbot\gauss\bot.py", line 59, in on_message
    response = do_integration(message)
  File "C:\Users\KenoK\PycharmProjects\gaussbot\gauss\brain.py", line 82, in do_integration
    integrand = to_sympy(integral)
  File "C:\Users\KenoK\PycharmProjects\gaussbot\gauss\parse.py", line 44, in to_sympy
    return parse_expr(message, transformations=transformations,
  File "C:\Users\KenoK\Anaconda3\envs\gaussbot\lib\site-packages\sympy\parsing\sympy_parser.py", line 1008, in parse_expr
    return eval_expr(code, local_dict, global_dict)
  File "C:\Users\KenoK\Anaconda3\envs\gaussbot\lib\site-packages\sympy\parsing\sympy_parser.py", line 902, in eval_expr
    expr = eval(
  File "<string>", line 0
    
    ^
SyntaxError: unexpected EOF while parsing

Traceback (most recent call last):
  File "C:\Users\KenoK\PycharmProjects\gaussbot\gauss\bot.py", line 59, in on_message
    response = do_integration(message)
  File "C:\Users\KenoK\PycharmProjects\gaussbot\gauss\brain.py", line 101, in do_integration
    _save_input(integrand, intvar, limits=limits)
  File "C:\Users\KenoK\PycharmProjects\gaussbot\gauss\brain.py", line 214, in _save_input
    save_as_png(Integral(integrand, intvar), VIEW_INPUT)
  File "C:\Users\KenoK\Anaconda3\envs\gaussbot\lib\site-packages\sympy\integrals\integrals.py", line 87, in __new__
    obj = AddWithLimits.__new__(cls, function, *symbols, **assumptions)
  File "C:\Users\KenoK\Anaconda3\envs\gaussbot\lib\site-packages\sympy\concrete\expr_with_limits.py", line 494, in __new__
    pre = _common_new(cls, function, *symbols, **assumptions)
  File "C:\Users\KenoK\Anaconda3\envs\gaussbot\lib\site-packages\sympy\concrete\expr_with_limits.py", line 48, in _common_new
    limits, orientation = _process_limits(*symbols)
  File "C:\Users\KenoK\Anaconda3\envs\gaussbot\lib\site-packages\sympy\concrete\expr_with_limits.py", line 156, in _process_limits
    raise ValueError('Invalid limits given: %s' % str(symbols))
ValueError: Invalid limits given: (I*H*d*n*o*s*exp(3),)

Traceback (most recent call last):
  File "C:\Users\KenoK\PycharmProjects\gaussbot\gauss\bot.py", line 59, in on_message
    response = do_integration(message)
  File "C:\Users\KenoK\PycharmProjects\gaussbot\gauss\brain.py", line 80, in do_integration
    integrand, limits = _sep_integrand(integral)
  File "C:\Users\KenoK\PycharmProjects\gaussbot\gauss\brain.py", line 147, in _sep_integrand
    integrand = to_sympy(integral.split('from')[0])
  File "C:\Users\KenoK\PycharmProjects\gaussbot\gauss\parse.py", line 44, in to_sympy
    return parse_expr(message, transformations=transformations,
  File "C:\Users\KenoK\Anaconda3\envs\gaussbot\lib\site-packages\sympy\parsing\sympy_parser.py", line 1008, in parse_expr
    return eval_expr(code, local_dict, global_dict)
  File "C:\Users\KenoK\Anaconda3\envs\gaussbot\lib\site-packages\sympy\parsing\sympy_parser.py", line 902, in eval_expr
    expr = eval(
  File "<string>", line 0
    
    ^
SyntaxError: unexpected EOF while parsing

Traceback (most recent call last):
  File "C:\Users\KenoK\PycharmProjects\gaussbot\gauss\bot.py", line 59, in on_message
    response = do_integration(message)
  File "C:\Users\KenoK\PycharmProjects\gaussbot\gauss\brain.py", line 80, in do_integration
    integrand, limits = _sep_integrand(integral)
  File "C:\Users\KenoK\PycharmProjects\gaussbot\gauss\brain.py", line 147, in _sep_integrand
    integrand = to_sympy(integral.split('from')[0])
  File "C:\Users\KenoK\PycharmProjects\gaussbot\gauss\parse.py", line 44, in to_sympy
    return parse_expr(message, transformations=transformations,
  File "C:\Users\KenoK\Anaconda3\envs\gaussbot\lib\site-packages\sympy\parsing\sympy_parser.py", line 1008, in parse_expr
    return eval_expr(code, local_dict, global_dict)
  File "C:\Users\KenoK\Anaconda3\envs\gaussbot\lib\site-packages\sympy\parsing\sympy_parser.py", line 902, in eval_expr
    expr = eval(
  File "<string>", line 0
    
    ^
SyntaxError: unexpected EOF while parsing

Traceback (most recent call last):
  File "C:\Users\KenoK\PycharmProjects\gaussbot\gauss\bot.py", line 55, in on_message
    set_greeting(message)
  File "C:\Users\KenoK\PycharmProjects\gaussbot\gauss\brain.py", line 58, in set_greeting
    if message.user.id == identity:
AttributeError: 'Message' object has no attribute 'user'

Traceback (most recent call last):
  File "C:\Users\KenoK\PycharmProjects\gaussbot\gauss\bot.py", line 55, in on_message
    await set_greeting(message)
  File "C:\Users\KenoK\PycharmProjects\gaussbot\gauss\brain.py", line 75, in set_greeting
    "gesetzt".format(greetings[key]))
NameError: name 'greeting' is not defined

Traceback (most recent call last):
  File "C:\Users\KenoK\PycharmProjects\gaussbot\gauss\bot.py", line 70, in on_message
    response = do_integration(message)
  File "C:\Users\KenoK\PycharmProjects\gaussbot\gauss\brain.py", line 127, in do_integration
    integrand = to_sympy(integral)
  File "C:\Users\KenoK\PycharmProjects\gaussbot\gauss\parse.py", line 48, in to_sympy
    return parse_expr(message, transformations=transformations,
  File "C:\Users\KenoK\Anaconda3\envs\gaussbot\lib\site-packages\sympy\parsing\sympy_parser.py", line 1003, in parse_expr
    code = stringify_expr(s, local_dict, global_dict, transformations)
  File "C:\Users\KenoK\Anaconda3\envs\gaussbot\lib\site-packages\sympy\parsing\sympy_parser.py", line 887, in stringify_expr
    for toknum, tokval, _, _, _ in generate_tokens(input_code.readline):
  File "C:\Users\KenoK\Anaconda3\envs\gaussbot\lib\tokenize.py", line 521, in _tokenize
    raise TokenError("EOF in multi-line statement", (lnum, 0))
tokenize.TokenError: ('EOF in multi-line statement', (2, 0))

